### ISSUE TITLE
Decide how to organize lab activity on two wikis

### ISSUE THREAD

**Issue by trecagroecology** [TREC-Agroecology/lab-wiki#1]
The other wiki is at the Open Science Framework (https://osf.io/bpe85/)

GitHub
- data, code, analysis
- lab wiki

OSF
- writing and manuscript prep
- paper library (?)
- large file upload (?)

**Comment by brymz** [comment]
For the time being the decision is to use a combination of GitHub and the shared `Agronomy/` folder -
Instructions at the [Lab Operations wiki page](https://github.com/TREC-Agroecology/lab-wiki/wiki/Lab-Operations).
