### ISSUE TITLE
PlantingCovercropExpNov2018

### ISSUE THREAD

**Issue by wdlngtn** [TREC-Agroecology/lab-wiki#13]
Planting Cover Crop Experiment at TREC after 15 Nov 2018 rain delay
====
- [x] Evaluate field conditions, day 1 ------ Because of rainfall Thursday morning and (predicted) afternoon, planting was delayed from Thursday to Friday.

- [x] Evaluate field conditions. day 2 -------  Friday at 8 am, Team Agroecology will assemble in lab.  We will assess if the soil has dried enough to plant by 8:30 am. At which point we will chose to plant 0, 2, or 4 blocks that day.

- [x] Planting ------- We will aim to begin planting 8:30 with extra help from three members of the field crew to accelerate. Plan A is to complete two blocks before lunch and two blocks after lunch on the same day, this may be reconsidered depending on soil conditions.

#conditions were ideal, glad we waited
#5 field crew members helped out
#Between 8:46 and 11:56, we competed the first three blocks
#Each block took approx 50 minutes on average

- [x] Complete Planting  ------- The experiment will be planted by the end of the day Friday, unless there is another delay. Issue will be closed

**Comment by Thioro18** [comment]
This is awesome Will, thank you.

**Comment by wdlngtn** [comment]
The rain missed us this afternoon. Friday should be good to plant.
