### ISSUE TITLE
Cumulative list of plant species from all TREC plant diversity plots 

### ISSUE THREAD

**Issue by cliffgmartin1** [TREC-Agroecology/lab-wiki#14]
Zack: Could you possibly send me the complete list of plant species found in all the plant diversity surveys (ideally in a sortable form)?  I think you mentioned there were about 206 species.  This would allow me to update the species to their latest correct names before publication.
Thanks

**Comment by brymz** [comment]
This issue is better for the `plant-diversity` repository: https://github.com/TREC-Agroecology/plant-diversity/issues
