### ISSUE TITLE
Zack and Wendy's First Blog Post

### ISSUE THREAD

**Issue by brymz** [TREC-Agroecology/lab-wiki#2]
The theme should be "What is Agroecology?"

**Comment by mesawendy0** [comment]
Questions and Flow of the Blog Posts

1. Is the "What is Agroecology (Shortened version)" format approved?
2. When would you like the Document to be posted?
3. Would you like future Documents to be written all at the same time before we begin to post, or would they be fine being written a week in advanced with the current structure of the first blog?
4. What is being done with the extended writing on the Faculty, is that being dismissed?

Once these questions have been answered I will be able to give you dates.

-Wendy

**Comment by brymz** [comment]
> 1. Is the "What is Agroecology (Shortened version)" format approved?

Yes! I like it. I see some more links to be added and a revision to the Qualitrics Survey, but overall the format is good.

> 2. When would you like the Document to be posted?

My goal is to post it by the end of the month. You'll have to make it through some of the 'Blogging Basics' course to make sure you're familiar with that process.

> 3. Would you like future Documents to be written all at the same time before we begin to post, or
> would they be fine being written a week in advanced with the current structure of the first blog?

We will begin to stagger blog development and posting. My goal is to write faster than we post, so we can build up a strong set of content to roll out. I'm thinking a new post every other week.

> 4. What is being done with the extended writing on the Faculty, is that being dismissed?

Nope. We will have two 'flavors' of post: agroecology content/training and agroecology in practice highlights. We can decide what to do with the laurel wilt team highlight as we put together a schedule for blog posts. The options are post immediately after part 1 or leave for a later week that we are behind on material.

**Comment by mesawendy0** [comment]
-I am not exactly sure what more links would be added.

**Comment by brymz** [comment]
That's ok. I'll have a look at it next and add any I think of.
