### ISSUE TITLE
Systems Concept for Agroecology post

### ISSUE THREAD

**Issue by brymz** [TREC-Agroecology/lab-wiki#6]
Zack needs to review Wendy's draft with specific comments.

**Comment by mesawendy0** [comment]
It is in the Draft section (Systems Outline)

**Comment by brymz** [comment]
My comments and revision are complete in `BlogSeries/Drafts/Systems-View-in-Agroecology.docx`. I like how this post is shaping up to deliver a solid message in a succinct way. Good work.

**Comment by mesawendy0** [comment]
I replied to your comments and saved it to the draft on the shared folder. The design sounds interesting, Not exactly sure how it would be done on the blog format.

**Comment by brymz** [comment]
Thanks. The water and plant systems diagram/table? I am thinking it would be a table developed in Excel or PowerPoint that would be inserted in the blog as a picture. You might already have a .ppt file with the Agroecosystems Scale image.

**Comment by mesawendy0** [comment]
![capture](https://user-images.githubusercontent.com/35775909/37849486-50335754-2eae-11e8-8df7-42aab45a60b8.JPG)
This one?

**Comment by brymz** [comment]
Nope. The one that is already inserted into the blog post with the pictures and description of organism, population, community, etc.

**Comment by mesawendy0** [comment]
So, What you are wanting is an eventual zoomed out version of water, rather than using the description, just a drawing of it? Also what is the existing plant system example? Sorry for the confusion.

**Comment by brymz** [comment]
I like the text in the highlight box. We’ll keep that. I like the accompanying graphic. I’m asking to modify that to include water and plant systems. My idea is something like:

 water | plants
drop   | organism
pool   | population
streams| community

Each section has a description and/or picture of the scale.

**Comment by brymz** [comment]
http://blogs.ifas.ufl.edu/trec/2018/05/25/agroecology-first-principle-system/
