### ISSUE TITLE
TREC_Plant Diversity Survey (PDS)

### ISSUE THREAD

**Issue by Thioro18** [TREC-Agroecology/lab-wiki#8]
Hi Dr. Brym,

Where are we going to install the the South block of the PDS in the Hammock? I was going over the design and I can't figure out the South side for Block 3.

Thank you
Thioro

**Comment by brymz** [comment]
The south PDS block in Block 3 is the one that we already installed and sampled. The north side will be located across the road. Not sure yet if we will straddle the road or set up just beyond it.
