### ISSUE TITLE
Systems Ambiguity

### ISSUE THREAD

**Issue by mesawendy0** [TREC-Agroecology/lab-wiki#9]
1- Are we wanting to focus on the Scales and boundaries of an agroecosystem?
2-What about Transformative agricultural landscapes using landscape ecology (which would entail understanding the role that the scale has on your system?)
3-Do you have any recommendations on sites about learning the basics of landscape ecology (I am not having any luck finding anything useful.)

**Comment by brymz** [comment]
Is this in reference to #6 or something more broad?

> 1- Are we wanting to focus on the Scales and boundaries of an agroecosystem?

Yes, in part. When thinking about agroecosystems, the scales and boundaries are the most basic parts to communicate, followed by the 'players' (i.e., species), and then the dynamics of the system through space and time. My choice in focus depends on the communication media. For example, my data science talk only made it to the scales/boundaries, but our IST should get through it all.

> 2-What about Transformative agricultural landscapes using landscape ecology (which would entail > understanding the role that the scale has on your system?)

I'm not familiar with this term: "transformative agricultural landscapes". Tell me more about what you mean. Landscape ecology is certainly an important subdiscipline to understand broader scales. Landscape ecology can also be called 'biogeography' and is used to understand ecological phenomena such as 'habitat fragmentation', 'metapopulations', and 'metacommunities'.

> 3-Do you have any recommendations on sites about learning the basics of landscape ecology (I 
> am not having any luck finding anything useful.)

Have a search for those other terms and see if something comes up. There is also a journal called 'Landscape Ecology', which might have a useful review (https://link.springer.com/article/10.1007/BF00133027; https://link.springer.com/content/pdf/10.1007/s10980-006-7195-2.pdf). The person that started landscape ecology is, Robert McArthur with his Theory of Island Biogeography. If you get me back Gliessman's book, I can loan you Nature's Matrix by Ivette Perfecto. She writes about landscape ecology for agriculture.

**Comment by mesawendy0** [comment]
If you tell me where it is located in your office, I will grab it on Monday, and leave the Gliessman in its place.
correction, transformation of agricultural landscapes
https://link.springer.com/article/10.1023/A:1008144402408

**Comment by brymz** [comment]
Cool paper! We’ll definitely want to cite/link to it. I’ll have to get you the book when I’m back in town,Tues or Wed.

**Comment by brymz** [comment]
Got you the book. Did we resolve this issue?

**Comment by mesawendy0** [comment]
I believe so
